<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-9" />
<title>Untitled Document</title>
<style type="text/css">
<!--
.style1 {font-family: Arial, Helvetica, sans-serif}
.style3 {font-family: Arial, Helvetica, sans-serif;
	color: #000000;
	font-size: 13px;
	font-style:normal;}
.style4 {color: #000000}
.style5 {
	font-family: Arial, Helvetica, sans-serif;
	color: #000000;
	font-size: 13px;
	font-style:normal;
	border-top-width: 1px;
	border-bottom-width: 1px;
border-right-width: 1px;
border-left-width: 1px;
border-top-style: solid;
border-right-style: solid;
border-bottom-style: solid;
border-left-style: solid;
border-top-color: #0066CC;
border-right-color: #0066CC;
border-left-color: #0066CC;
border-bottom-color: #0066CC;
}
.style6 {
font-family: Arial, Helvetica, sans-serif;
	color: #000000;
	font-size: 13px;
	font-style:normal;	
	border-style:none;
	
}
-->
</style>
<script language="JavaScript" src="toplama.js" type="text/javascript">
</script>	
</head>
<?php
include('con_023.php');
$ilgelen=iconv("UTF-8", "ISO-8859-9", $_GET['selectil']); 
$ilcegelen=iconv("UTF-8", "ISO-8859-9", $_GET['selectilce']); 
$ocgelen=iconv("UTF-8", "ISO-8859-9", $_GET['selectoc']); 
$yilgelen=$_GET['selectyil'];
$aygelen=iconv("UTF-8", "ISO-8859-9", $_GET['selectay']); 
$ocakyazi=iconv("UTF-8", "ISO-8859-9", $_GET['selectoc']);
/*echo $ilgelen ;
echo $ilcegelen ;
echo $ocgelen ;
echo $yilgelen ;
echo $aygelen ;*/
?>
<body>
<div style="font-family:Arial, Helvetica, sans-serif" style="font-size:14px" id="sonuc"></div>

<?php
$resultvyil = @mysql_query("select * from veri where(ilidi='$ilgelen' and ilceidi='$ilcegelen' and vocadi='$ocgelen' and vyiladi='$yilgelen' and vayadi='$aygelen')") ;
while($sonucum=mysql_fetch_array($resultvyil)){
$ilim=$sonucum['ilidi'];
$ilcem=$sonucum['ilceidi'];
$socadi=$sonucum['vocadi'];
$yilim=$sonucum['vyiladi'];
$ayim=$sonucum['vayadi'];
$verim1=$sonucum['v1'];
$verim2=$sonucum['v2'];
$verim3=$sonucum['v3'];
$verim4=$sonucum['v4'];
$verim5=$sonucum['v5'];
$verim6=$sonucum['v6'];
$verim7=$sonucum['v7'];
$verim8=$sonucum['v8'];
$verim9=$sonucum['v9'];
$verim10=$sonucum['v10'];
$verim11=$sonucum['v11'];
$verim12=$sonucum['v12'];
$verim13=$sonucum['v13'];
$verim14=$sonucum['v14'];
$verim15=$sonucum['v15'];
$verim16=$sonucum['v16'];
$verim17=$sonucum['v17'];
$verim18=$sonucum['v18'];
$verim19=$sonucum['v19'];
$verim20=$sonucum['v20'];
$verim21=$sonucum['v21'];
$verim22=$sonucum['v22'];
$verim23=$sonucum['v23'];
$verim24=$sonucum['v24'];
$verim25=$sonucum['v25'];
$verim26=$sonucum['v26'];
$verim27=$sonucum['v27'];
$verim28=$sonucum['v28'];
$verim29=$sonucum['v29'];
$verim30=$sonucum['v30'];
$verim31=$sonucum['v31'];
$verim32=$sonucum['v32'];
$verim33=$sonucum['v33'];
$verim34=$sonucum['v34'];
$verim35=$sonucum['v35'];
$verim36=$sonucum['v36'];
$verim37=$sonucum['v37'];
$verim38=$sonucum['v38'];
$verim39=$sonucum['v39'];
$verim40=$sonucum['v40'];
$verim41=$sonucum['v41'];
$verim42=$sonucum['v42'];
$verim43=$sonucum['v43'];
$verim44=$sonucum['v44'];
$verim45=$sonucum['v45'];
$verim46=$sonucum['v46'];
$verim47=$sonucum['v47'];
$verim48=$sonucum['v48'];
$verim49=$sonucum['v49'];
$verim50=$sonucum['v50'];
$verim51=$sonucum['v51'];
$verim52=$sonucum['v52'];
$verim53=$sonucum['v53'];
$verim54=$sonucum['v54'];
$verim55=$sonucum['v55'];
$verim56=$sonucum['v56'];
$verim57=$sonucum['v57'];
$verim58=$sonucum['v58'];
$verim59=$sonucum['v59'];
$verim60=$sonucum['v60'];
$verim61=$sonucum['v61'];
$verim62=$sonucum['v62'];
$verim63=$sonucum['v63'];
$verim64=$sonucum['v64'];
$verim65=$sonucum['v65'];
$verim66=$sonucum['v66'];
$verim67=$sonucum['v67'];
$verim68=$sonucum['v68'];
$verim69=$sonucum['v69'];
$verim70=$sonucum['v70'];
$verim71=$sonucum['v71'];
$verim72=$sonucum['v72'];
$verim73=$sonucum['v73'];
$verim74=$sonucum['v74'];
$verim75=$sonucum['v75'];
$verim76=$sonucum['v76'];
$verim77=$sonucum['v77'];
$verim78=$sonucum['v78'];
$verim79=$sonucum['v79'];
$verim80=$sonucum['v80'];
$verim81=$sonucum['v81'];
$verim82=$sonucum['v82'];
$verim83=$sonucum['v83'];
$verim84=$sonucum['v84'];
$verim85=$sonucum['v85'];
$verim86=$sonucum['v86'];
$verim87=$sonucum['v87'];
$verim88=$sonucum['v88'];
$verim89=$sonucum['v89'];
$verim90=$sonucum['v90'];
$verim91=$sonucum['v91'];
$verim92=$sonucum['v92'];
$verim93=$sonucum['v93'];
$verim94=$sonucum['v94'];
$verim95=$sonucum['v95'];
$verim96=$sonucum['v96'];
$verim97=$sonucum['v97'];
$verim98=$sonucum['v98'];
$verim99=$sonucum['v99'];
$verim100=$sonucum['v100'];
$verim101=$sonucum['v101'];
$verim102=$sonucum['v102'];
$verim103=$sonucum['v103'];
$verim104=$sonucum['v104'];
$verim105=$sonucum['v105'];
$verim106=$sonucum['v106'];
$verim107=$sonucum['v107'];
$verim108=$sonucum['v108'];
$verim109=$sonucum['v109'];
$verim110=$sonucum['v110'];
$verim111=$sonucum['v111'];
$verim112=$sonucum['v112'];
$verim113=$sonucum['v113'];
$verim114=$sonucum['v114'];
$verim115=$sonucum['v115'];
$verim116=$sonucum['v116'];
$verim117=$sonucum['v117'];
$verim118=$sonucum['v118'];
$verim119=$sonucum['v119'];
$verim120=$sonucum['v120'];
$verim121=$sonucum['v121'];
$verim122=$sonucum['v122'];
$verim123=$sonucum['v123'];
$verim124=$sonucum['v124'];
$verim125=$sonucum['v125'];
$verim126=$sonucum['v126'];
$verim127=$sonucum['v127'];
$verim128=$sonucum['v128'];
$verim129=$sonucum['v129'];
$verim130=$sonucum['v130'];
$verim131=$sonucum['v131'];
$verim132=$sonucum['v132'];
$verim133=$sonucum['v133'];
$verim134=$sonucum['v134'];
$verim135=$sonucum['v135'];
$verim136=$sonucum['v136'];
$verim137=$sonucum['v137'];
$verim138=$sonucum['v138'];
$verim139=$sonucum['v139'];
$verim140=$sonucum['v140'];
$verim141=$sonucum['v141'];
$verim142=$sonucum['v142'];
$verim143=$sonucum['v143'];
$verim144=$sonucum['v144'];
$verim145=$sonucum['v145'];
$verim146=$sonucum['v146'];
$verim147=$sonucum['v147'];
$verim148=$sonucum['v148'];
$verim149=$sonucum['v149'];
$verim150=$sonucum['v150'];
$verim151=$sonucum['v151'];
$verim152=$sonucum['v152'];
$verim153=$sonucum['v153'];
$verim154=$sonucum['v154'];
$verim155=$sonucum['v155'];
$verim156=$sonucum['v156'];
$verim157=$sonucum['v157'];
$verim158=$sonucum['v158'];
$verim159=$sonucum['v159'];
$verim160=$sonucum['v160'];
$verim161=$sonucum['v161'];
$verim162=$sonucum['v162'];
$verim163=$sonucum['v163'];
$verim164=$sonucum['v164'];
$verim165=$sonucum['v165'];
$verim166=$sonucum['v166'];
$verim167=$sonucum['v167'];
$verim168=$sonucum['v168'];
$verim169=$sonucum['v169'];
$verim170=$sonucum['v170'];
$verim171=$sonucum['v171'];
$verim172=$sonucum['v172'];
$verim173=$sonucum['v173'];
$verim174=$sonucum['v174'];
$verim175=$sonucum['v175'];
$verim176=$sonucum['v176'];
$verim177=$sonucum['v177'];
$verim178=$sonucum['v178'];
$atarih=mysql_query("SELECT date_format(v175, '%d.%m.%Y')  AS yeni_tarih FROM veri where(ilidi='$ilgelen' and ilceidi='$ilcegelen' and vocadi='$ocgelen' and vyiladi='$yilgelen' and vayadi='$aygelen')") ;
while($duztarih=mysql_fetch_array($atarih)){
$dtarih=$duztarih['yeni_tarih'];
}
$btarih=mysql_query("SELECT date_format(v178, '%d.%m.%Y')  AS yeni_tarih FROM veri where(ilidi='$ilgelen' and ilceidi='$ilcegelen' and vocadi='$ocgelen' and vyiladi='$yilgelen' and vayadi='$aygelen')") ;
while($ontarih=mysql_fetch_array($btarih)){
$otarih=$ontarih['yeni_tarih'];
}
//echo $yilim;
}
$toplam1=$verim4+$verim5;
$toplam2=$verim7+$verim8+$verim9+$verim10+$verim11;
$toplame=$verim24+$verim26+$verim28+$verim30+$verim32+$verim34+$verim36+$verim38+$verim40+$verim42+$verim44;
$toplamk=$verim25+$verim27+$verim29+$verim31+$verim33+$verim35+$verim37+$verim39+$verim41+$verim43+$verim45;
$toplames=$verim46+$verim47+$verim48+$verim49+$verim50+$verim51+$verim52+$verim53+$verim54+$verim55+$verim56+$verim57;
$toplamhs=$verim58+$verim59+$verim60+$verim61+$verim62+$verim63+$verim64+$verim65+$verim66+$verim67+$verim68+$verim69;
$toplamhes=$verim70+$verim71+$verim72+$verim73+$verim74+$verim75+$verim76+$verim77+$verim78+$verim79+$verim80+$verim81;
$toplamsm=$verim82+$verim83+$verim84+$verim85+$verim86+$verim87+$verim88+$verim89+$verim90+$verim91+$verim92+$verim93;
$toplameb=$verim94+$verim95+$verim96+$verim97+$verim98+$verim99+$verim100+$verim101+$verim102+$verim103+$verim104+$verim105;
$toplamd=$verim106+$verim107+$verim108+$verim109+$verim110+$verim111+$verim112+$verim113+$verim114+$verim115+$verim116+$verim117;
?>
<?php
$iladi=@mysql_query("select * from il where(ilid='$ilim')");
while($ilsonucum=mysql_fetch_array($iladi)){
$ilinadi=$ilsonucum['ilad'];
}
?>
<?php
$ilceadi=@mysql_query("select * from ilce where(ilinad='$ilim' and ilceid='$ilcem')");
while($ilcesonucum=mysql_fetch_array($ilceadi)){
$ilceninadi=$ilcesonucum['ilcead'];
}
?>
<?php
//$degsayfa="http://localhost/form023/frm023degistir.php?ilgelen=".$ilim."&ilcegelen=".$ilcem."&ocgelen=".$socadi."&yilgelen=".$yilim."&aygelen=".$ayim."";
//$silsayfa="http://localhost/form023/023sil.php?ilgelen=".$ilim."&ilcegelen=".$ilcem."&ocgelen=".$socadi."&yilgelen=".$yilim."&aygelen=".$ayim."";
echo'<table border="0" bordercolor="#000000" align="left" cellpadding="0" cellspacing="0" width="100%">';
echo'<tr>';
	echo '<th class="style6" width="5%"align="left" bordercolor="white" bgcolor="yellow" colspan="28"><a href=# onClick="kontrol();"><img src="images/geri.png"></a></th>';
	echo '<th class="style6" width="5%"align="left" bordercolor="white" bgcolor="yellow" colspan="0"><a href=# onClick="deg();"><img src="images/degistir.png"></a></th>';	
	echo '<th class="style6" width="5%"align="left" bordercolor="white" bgcolor="yellow" colspan="0"><a href=# onClick="onay();"><img src="images/sil.png"></a></th>';
	echo '</tr>';
echo '<tr>';
    echo '<th class="style6" width="5%" align="center"bordercolor="white" bgcolor="white" colspan="1" class="style5">İL:</th>';
    echo '<th class="style6" width="5%"align="left" bordercolor="white" bgcolor="white" colspan="8" class="style5">&nbsp;'.$ilinadi.'</th>';
    echo '<th class="style6" width="5%"align="center" bordercolor="white" bgcolor="white" colspan="1"></th>';
	echo '<th class="style6" width="5%" align="center"bordercolor="white" bgcolor="white" colspan="3">KURUM:</th>';
	echo '<th class="style6" width="5%"align="left" bordercolor="white" bgcolor="white" colspan="14">&nbsp;'.$ocakyazi.'</th>'; 
	echo '<th class="style6" width="5%" align="center"bordercolor="white" bgcolor="white" colspan="1">YIL:</th>';
	echo '<th class="style6" width="5%"align="left" bordercolor="white" bgcolor="white" colspan="3">&nbsp;'.$yilim.'</th>';
	echo '</tr>';
echo'<tr>';
    echo '<th class="style6" width="5%" align="center"bordercolor="white" bgcolor="white" colspan="1">İLÇE:</th>';
    echo '<th class="style6" width="5%"align="left" bordercolor="white" bgcolor="white" colspan="22">&nbsp;'.$ilceninadi.'</th>';
	echo '<th class="style6" width="5%"align="center" bordercolor="white" bgcolor="white" colspan="4"></th>';
	echo '<th class="style6" width="5%" align="center"bordercolor="white" bgcolor="white" colspan="1">AY:</th>';
	echo '<th class="style6" width="5%"align="left" bordercolor="white" bgcolor="white" colspan="1">&nbsp;'.$ayim.'</th>';
   	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Muayene Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim1.' </th>';
	echo '<th class="style6" width="5%" align=""  bgcolor="white" colspan="9" rowspan="8"></th>'; 
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" rowspan="6" colspan="1">DO<br>ĞUM<br>LAR</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Hastanede</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim7.' </th>';
    echo '</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Sağlık Kurumuna Sevk</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim2.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Hekim</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim8.' </th>';
    echo '</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Küçük Cerrahi Müdahale</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim3.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Ebe</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim9.' </th>';
    echo '</tr>';
echo'<tr class="style5">';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" rowspan="3" colspan="1">ADLİ</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Klasik Otopsi Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim4.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Diğer Sağlık Personeli Yardımı ile</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim10.' </th>';
    echo '</tr>';
echo'<tr class="style5">';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Adli Rapor Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim5.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Sağlık Personeli Yardımı Olmadan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim11.' </th>';
    echo '</tr>';
echo'<tr class="style5">';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Toplam</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$toplam1.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;TOPLAM</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$toplam2.' </th>';
    echo '</tr>';
echo'<tr class="style5">';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Defin Ruhsatı Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim6.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" rowspan="6" colspan="1">İZ<br>LEM<br>LER</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Gebe</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim19.' </th>';
    echo '</tr>';	
echo'<tr class="style5">';
    echo '<th class="style6" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="11"></th>';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Loğusa</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim20.' </th>';
    echo '</tr>';
echo'<tr class="style5">';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="19">LABARATUVAR ÇALIŞMALARI</th>';
	echo '<th class="style6" width="5%" align=""  bgcolor="white" colspan="1" rowspan="3"></th>';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Bebek</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim21.' </th>';
    echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="1"></th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">İdrar</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">Kan</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">Dışkı</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">Seroloji</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">Sıtma Kanı</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">Geb.Testi</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">Diğer</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Çocuk</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim22.' </th>';
    echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">Sayı</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim12.'</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim13.'</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim14.'</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim15.'</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim16.'</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim17.'</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim18.'</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;15-49 Yaş Kadın</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim23.' </th>';
	    echo '</tr>';	
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="white" bgcolor="white" colspan="32"><br></th>';
	echo'</tr>';			
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="#000000" bgcolor="white" colspan="32">BÜTÜN ÖLENLERİN YAŞ VE CİNS GRUPLARINA GÖRE DAĞILIMI</th>';
	echo'</tr>';
echo'<tr>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">Yaş</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">0-7 Gün</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">8-28 Gün</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">29-364 Gün</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">1-4 Yaş</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">5-9 Yaş</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">10-14 Yaş</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">15-24 Yaş</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">25-44 Yaş</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">45-49 Yaş</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">50-64 Yaş</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">65 + Yaş</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="8">TOPLAM</th>';
    echo '</tr>';		
echo'<tr>';
	echo '<th class="style5" width="3%" align="left"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;Cinsiyet</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">K</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">K</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">K</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">K</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">K</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">K</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">K</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">K</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">K</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">K</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">K</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="4">E</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="4">K</th>';
    echo '</tr>';		
echo'<tr>';
	echo '<th class="style5" width="3%" align="left"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;Sayı</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim24.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim25.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim26.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim27.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim28.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim29.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim30.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim31.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim32.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim33.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim34.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim35.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim36.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim37.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim38.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim39.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim40.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim41.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim42.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim43.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim44.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim45.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$toplame.'</th>';
	echo '<th class="style5" width="3%" align="center"bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$toplamk.'</th>';
    echo '</tr>';	
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="white" bgcolor="white" colspan="32"><br></th>';
	echo'</tr>';			
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="#000000" bgcolor="white" colspan="32">HALK EĞİTİMİ VE HİZMETİÇİ EĞİTİMLERİN SEANS SAYILARI</th>';
	echo'</tr>';
echo'<tr>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="5">Konular</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">01</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">02</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">03</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">04</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">05</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">06</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">07</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">08</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">09</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">10</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">11</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">12</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">TOPLAM</th>';
    echo '</tr>';		
echo'<tr>';
	echo '<th class="style5" width="6%" align="left"bordercolor="#000000" bgcolor="white" colspan="5">&nbsp;HALK EĞİTİMİ</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim46.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim47.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim48.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim49.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim50.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim51.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim52.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim53.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim54.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim55.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim56.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim57.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$toplames.'</th>';
    echo '</tr>';	
echo'<tr>';
	echo '<th class="style5" width="6%" align="left"bordercolor="#000000" bgcolor="white" colspan="1" rowspan="5">HİZMET İÇİ EĞİTİM</th>';
	echo '<th class="style5" width="6%" align="left"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;Hekim</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim58.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim59.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim60.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim61.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim62.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim63.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim64.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim65.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim66.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim67.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim68.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim69.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$toplamhs.'</th>';
    echo '</tr>';	
echo'<tr>';
	echo '<th class="style5" width="6%" align="left"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;Hemşire</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim70.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim71.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim72.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim73.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim74.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim75.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim76.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim77.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim78.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim79.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim80.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim81.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$toplamhes.'</th>';
    echo '</tr>';
echo'<tr>';
	echo '<th class="style3" width="6%" align="left"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;<font size="2">Sağ.Mem.</font></th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim82.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim83.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim84.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim85.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim86.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim87.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim88.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim89.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim90.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim91.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim92.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim93.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$toplamsm.'</th>';
    echo '</tr>';	
echo'<tr>';
	echo '<th class="style5" width="6%" align="left"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;Ebe</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim94.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim95.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim96.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim97.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim98.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim99.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim100.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim101.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim102.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim103.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim104.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim105.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$toplameb.'</th>';
    echo '</tr>';
echo'<tr>';
	echo '<th class="style3" width="6%" align="left"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;Diğer Personel</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim106.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim107.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim108.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim109.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim110.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim111.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim112.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim113.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim114.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim115.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="3">&nbsp;'.$verim116.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="1">&nbsp;'.$verim117.'</th>';
	echo '<th class="style5" width="6%" align="center"bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$toplamd.'</th>';
    echo '</tr>';
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="white" bgcolor="white" colspan="30"><br></th>';
	echo'</tr>';			
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="#000000" bgcolor="white" colspan="30"></th>';
	echo'</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="12">GEBE DURUMU</th>';
	echo '<th class="style5" width="5%" align=""  bgcolor="white" colspan="6" rowspan="10"></th>';
    echo '<th class="style5" width="5%" align="center" bordercolor="#000000" bgcolor="white" colspan="12">BEBEK DURUMU</th>';
    echo '</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">a</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Geçen Aydan Devreden</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim118.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">a</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Geçen Aydan Devreden</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim127.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">b</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay İçinde Tesbit Edilen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim119.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">b</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay İçinde Tesbit Edilen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim128.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">c</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Başka Bölgeden Gelen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim120.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">c</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Başka Bölgeden Gelen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim129.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">d</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay İçinde Düşük Yapan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim121.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">d</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay İçinde Canlı Doğan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim130.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">e</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay İçinde Doğuran</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim122.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">e</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay İçinde Ölen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim131.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">f</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay İçinde Ölen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim123.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">f</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bölgeden Ayrılan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim132.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">g</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bölgeden Ayrılan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim124.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">g</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bebeklikten Çıkan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim133.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" >h</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Ay Sonu Gebe Mevcudu<br>&nbsp;(a+b+c)-(d+e+f+g)</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim125.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">h</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Ay Sonu Bebek Mevcudu<br>&nbsp;(a+b+c+d)-(e+f+g)</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim134.' </th>'; 
	echo '</tr>';
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="white" bgcolor="white" colspan="30"><br></th>';
	echo'</tr>';			
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="#000000" bgcolor="white" colspan="30"></th>';
	echo'</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Doğum Anında Ölen Gebe Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim126.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="6"></th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Ölü Doğan Bebek Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim135.' </th>'; 
	echo '</tr>';
//LOHUSA-ÇOCUK DURUMU
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="white" bgcolor="white" colspan="30"><br></th>';
	echo'</tr>';			
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="#000000" bgcolor="white" colspan="30"></th>';
	echo'</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="12">LOHUSA DURUMU</th>';
	echo '<th class="style5" width="5%" align=""  bgcolor="white" colspan="6" rowspan="10"></th>';
    echo '<th class="style5" width="5%" align="center" bordercolor="#000000" bgcolor="white" colspan="12">ÇOCUK DURUMU</th>';
    echo '</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">a</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Geçen Aydan Devreden</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim136.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">a</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Geçen Aydan Devreden</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim144.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">b</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay İçinde Tesbit Edilen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim137.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">b</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay İçinde Tesbit Edilen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim145.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">c</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Başka Bölgeden Gelen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim138.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">c</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Başka Bölgeden Gelen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim146.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">d</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay Lohusalığa Geçen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim139.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">d</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay Çocukluğa Geçen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim147.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">e</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay İçinde Ölen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim140.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">e</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay İçinde Ölen</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim148.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">f</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bölgeden Ayrılan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim141.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">f</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bölgeden Ayrılan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim149.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">g</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Bu Ay Lohusalıktan Çıkan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim142.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">g</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Çocukluktan Çıkan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim150.' </th>'; 
	echo '</tr>';	
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" >h</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Ay Sonu Lohusa Mevcudu<br>&nbsp;(a+b+c+d)-(e+f+g)</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim143.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white">h</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="7">&nbsp;Ay Sonu Çocuk Mevcudu<br>&nbsp;(a+b+c+d)-(e+f+g)</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim151.' </th>'; 
	echo '</tr>';
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="white" bgcolor="white" colspan="30"><br></th>';
	echo'</tr>';			
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="#000000" bgcolor="white" colspan="30"></th>';
	echo'</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="12">DİŞ SAĞLIĞI BİLGİLERİ</th>';
	echo '<th class="style5" width="5%" align=""  bgcolor="white" colspan="1" rowspan="10"></th>';
    echo '<th class="style5" width="5%" align="center" bordercolor="#000000" bgcolor="white" colspan="17">DÜŞÜK DOĞUM AĞIRLIKLI BEBEK</th>';
    echo '</tr>';
echo'<tr>';	
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Muayene Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim152.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="13">&nbsp;Doğum Ağırlığı 1500 Gr.ın Altında Olan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim161.' </th>'; 
	echo '</tr>';	
echo'<tr>';	
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Okul Taramaları:Taranan Öğrenci Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim153.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="13">&nbsp;Doğum Ağırlığı 1500-2500 Gr. Arası Olan</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim162.' </th>'; 
	echo '</tr>';
echo'<tr>';	
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;12-45 Yaşta Tesbit Edilen Çürük Diş Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim154.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="22"></th>';
    echo '</tr>';	
echo'<tr>';	
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Tesbit Edilen Diş Hastalıkları Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim155.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="22"></th>';
    echo '</tr>';
echo'<tr>';	
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Tedavi Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim156.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="8">ÇOĞUL DOĞUMLAR</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8"></th>';
    echo '</tr>';	
echo'<tr>';	
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Çekim Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim157.' </th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="6">Özelliği</th>';
	echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="2">Sayısı</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8"></th>';
    echo '</tr>';	
echo'<tr>';	
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Sevk Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim158.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="6">&nbsp;İKİZ</th>';
	echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim163.'</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="2"></th>';
	echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="8">PREMATÜRE DOĞUM SAYISI</th>';
    echo '</tr>';
echo'<tr>';	
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;Flor Uygulaması</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim159.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="6">&nbsp;ÜÇÜZ</th>';
	echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim164.'</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="2"></th>';
	echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;'.$verim166.'</th>';
    echo '</tr>';
echo'<tr>';	
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="8">&nbsp;</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;'.$verim160.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="6">&nbsp;DÖRDÜZ</th>';
	echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="2">&nbsp;'.$verim165.'</th>';
	echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="8"></th>';
    echo '</tr>';
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="white" bgcolor="white" colspan="30"><br></th>';
	echo'</tr>';			
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="#000000" bgcolor="white" colspan="30">KUDUZ ŞÜPHELİ ISIRIK VE KUDUZ VAKALARI İLE UYGULANAN TEDAVİLER</th>';
	echo'</tr>';
echo'<tr>';	
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="5">Isırılan Kişi Sayısı</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="5">Kuduz Teşhis Edilen Kişi Sayısı</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="10">Kuduz Aşısı Uygulanan Kişiler<br> Yerli Aşı&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;İthal Aşı</th>';
	echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="5">Serum Uygulanan Kişi Sayısı</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="5">Karantinaya Alınan Kişi Sayısı</th>';
	echo '</tr>';	
echo'<tr>';	
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="5">&nbsp;'.$verim167.'</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="5">&nbsp;'.$verim168.'</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="5">&nbsp;'.$verim169.'</th>';
	echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="5">&nbsp;'.$verim170.'</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="5">&nbsp;'.$verim171.'</th>';
	echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="5">&nbsp;'.$verim172.'</th>';
	echo '</tr>';	
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="white" bgcolor="white" colspan="30"><br></th>';
	echo'</tr>';			
echo'<tr>';
	echo '<th class="style5" width="100%" align="center"bordercolor="#000000" bgcolor="white" colspan="30"></th>';
	echo'</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="center"bordercolor="#000000" bgcolor="white" colspan="13">DÜZENLEYEN</th>';
	echo '<th class="style5" width="5%" align=""  bgcolor="white" colspan="4" rowspan="5"></th>';
    echo '<th class="style5" width="5%" align="center" bordercolor="#000000" bgcolor="white" colspan="13">ONAYLAYAN</th>';
    echo '</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;Adı Soyadı</th>';
    echo '<th class="style5" width="5%"align="left" bordercolor="#000000" bgcolor="white" colspan="9">&nbsp;'.$verim173.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;Adı Soyadı</th>';
    echo '<th class="style5" width="5%"align="left" bordercolor="#000000" bgcolor="white" colspan="9">&nbsp;'.$verim176.' </th>'; 
	echo '</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;Ünvanı</th>';
    echo '<th class="style5" width="5%"align="left" bordercolor="#000000" bgcolor="white" colspan="9">&nbsp;'.$verim174.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;Ünvanı</th>';
    echo '<th class="style5" width="5%"align="left" bordercolor="#000000" bgcolor="white" colspan="9">&nbsp;'.$verim177.' </th>'; 
	echo '</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;Tarih</th>';
    echo '<th class="style5" width="5%"align="left" bordercolor="#000000" bgcolor="white" colspan="9">&nbsp;'.$dtarih.' </th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;Tarih</th>';
    echo '<th class="style5" width="5%"align="left" bordercolor="#000000" bgcolor="white" colspan="9">&nbsp;'.$otarih.' </th>'; 
	echo '</tr>';
echo'<tr>';
    echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;İmza</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="9">&nbsp;</th>';
	echo '<th class="style5" width="5%" align="left"bordercolor="#000000" bgcolor="white" colspan="4">&nbsp;İmza</th>';
    echo '<th class="style5" width="5%"align="center" bordercolor="#000000" bgcolor="white" colspan="9">&nbsp;</th>'; 
	echo '</tr>';		
	echo'</table>';  		
?>
</body>

</html>
